extends CharacterBody3D

const SPEED = 3.5
const JUMP_VELOCITY = 3.5

var walk_animation_time = 0
var face_rotation = 0
var face_left = false

var combatable = true

var iframes = 0
var knockback_time = 0
var health = 100

var slots = [
	{
		"id": "basic_sword",
		"cooldown": 0,
	},
	{
		"id": "basic_handcannon",
		"cooldown": 0,
	},
]

var combo_hits = 0
var combo_timer = 0
var swing_timer = 0

var queue_swing = false

var dodging = false
var dodge_timer = 0.0
var dodge_direction = null

var current_slot = 0
var current_weapon = "basic_sword"

enum {
	STATE_NORMAL,
	STATE_DODGING,
	STATE_ATTACK,
	STATE_HIT,
	STATE_DEATH
}

var state = STATE_NORMAL

@onready var game = get_parent()
@onready var camera = game.get_node("PlayerCamera")

func hit_me():
	iframes = 0.5
	health -= 10
	
func get_my_weapon_info(value: String):
	return get_weapon_info(current_weapon.id, value)
	
func get_weapon_info(weapon: String, value: String):
	if value in Global.weapons[weapon]: 
		return Global.weapons[weapon][value]
	else: return null
	
func on_hit(hitter: Node3D = null) -> void:
	iframes = 0.8
	
	if hitter:
		knockback_time = 0.25
		velocity += hitter.global_position.direction_to(global_position) * 8
		velocity.y = 0
		
func give_weapon(weapon_name: String = "basic_sword") -> void:
	pass
	
func set_weapon_from_slot(slot: int) -> void:
	current_slot = slot
	set_weapon(slots[slot])
	
func set_weapon(weapon_data: Dictionary) -> void:
	current_weapon = weapon_data
	$DreamerBody.set_inhand(weapon_data.id)
	
	var range = get_weapon_info(weapon_data.id, "range")
	if not range: range = 1
	var width = get_weapon_info(weapon_data.id, "width")
	if not width: width = 1
	
	$HitCollision/Shape.shape.size = Vector3(range, 1.0, width)
	
	$HitCollision/Shape.position.x = range * -0.5
	
func dps(weapon_name: String = "basic_sword") -> void:
	var damage = get_weapon_info(weapon_name, "damage")
	var time = get_weapon_info(weapon_name, "swing_time")
	
	if get_weapon_info(weapon_name, "combo_weapon"):
		var combo_damage = get_weapon_info(weapon_name, "damage_mid_combo") * get_weapon_info(weapon_name, "hits_to_finish")
		time *= float(get_weapon_info(weapon_name, "hits_to_finish"))
		time += float(get_weapon_info(weapon_name, "swing_time_combo_finish"))
	
	LimboConsole.print_line(str(damage / time))

func _ready() -> void:
	LimboConsole.register_command(hit_me)
	LimboConsole.register_command(set_weapon)
	LimboConsole.register_command(dps)
	set_weapon_from_slot(0)
	
func _process(delta: float) -> void:
	
	if iframes > 0:
		iframes -= delta
		$DreamerBody/Body.modulate.a = 0.5
	else:
		$DreamerBody/Body.modulate.a = 1
		
	if knockback_time > 0:
		knockback_time -= delta
		$DreamerBody/Animator.set("parameters/hit/blend_amount", 1.0)
	else:
		$DreamerBody/Animator.set("parameters/hit/blend_amount", 0.0)
		
	var i = 0
	while i < slots.size():
		if ("cooldown" in slots[i]) and (slots[i].cooldown > 0): slots[i].cooldown -= delta
		
		if Input.is_action_just_pressed("hotbar_item_" + str(i + 1)):
			set_weapon_from_slot(i)
			
		i += 1

	$DreamerBody.look_at(game.get_node("PlayerCamera").global_position)
	$DreamerBody.rotation.x = 0
	face_rotation = $DreamerBody.rotation.y
	if not face_rotation: face_rotation = 0
	
	if not is_on_floor():
		velocity += get_gravity() * delta
		
	var viewport_half = (get_viewport().get_visible_rect().size / 2.0)
	var player_position = camera.unproject_position(global_transform.origin)
	
	if face_left:
		$DreamerBody.rotation.y = face_rotation + deg_to_rad(180)
		$DreamerBody/Animator.set("parameters/layering/blend_amount", 1.0)
	else:
		$DreamerBody.rotation.y = face_rotation
		$DreamerBody/Animator.set("parameters/layering/blend_amount", 0.0)

	var input_dir := Input.get_vector("move_left", "move_right", "move_up", "move_down")
	if not combatable:
		if input_dir.x > 0:
			face_left = false
		if input_dir.x < 0:
			face_left = true
			
	var direction = (camera.transform.basis * Vector3(input_dir.x, 0, input_dir.y)).normalized()
		
	var mouse_point_angle
	if input_icon.using_gamepad:
		var direction_no_y = direction
		direction_no_y.y = 0
		
		var old_rotation = $HitCollision.rotation
		
		$HitCollision.look_at(global_position + direction_no_y)
		mouse_point_angle = -$HitCollision.rotation.y - deg_to_rad(45)
		
		$HitCollision.rotation = old_rotation
	else:
		mouse_point_angle = player_position.angle_to_point(get_viewport().get_mouse_position())
	
	if combatable:
		if ((swing_timer <= 0) or (combo_hits < 0)):
			$HitCollision.rotation.y = -mouse_point_angle + face_rotation
		
			if abs(rad_to_deg(mouse_point_angle) - (-90)) < 50:
				$HitCollision/Shape.shape.size.x = 1.5
			else:
				$HitCollision/Shape.shape.size.x = 1.2
			
			if (rad_to_deg(mouse_point_angle) < -90) or (rad_to_deg(mouse_point_angle) > 90):
				face_left = true
				
				var mouse_pos = get_viewport().get_mouse_position()
				mouse_pos.y = (viewport_half.y) + ((viewport_half.y) - mouse_pos.y)
				
				#$DreamerBody/Body/ArmPivot.rotation.z = viewport_half.angle_to_point(mouse_pos)
			else:
				face_left = false
				$DreamerBody/Body/ArmPivot.scale.y = 1
				$DreamerBody/Body/ArmPivot.scale.x = 1
			
		$DreamerBody/Animator.set("parameters/hold_weapon/blend_amount", 1.0)
	else:
		$DreamerBody/Body/ArmPivot.global_rotation.y = face_rotation
		$DreamerBody/Body/ArmPivot.scale.y = 1
		$DreamerBody/Body/ArmPivot.scale.x = 1
		$DreamerBody/Body/ArmPivot.rotation.z = 0
			
		$DreamerBody/Animator.set("parameters/hold_weapon/blend_amount", 0.0)
	
	if Input.is_action_pressed("jump") and is_on_floor():
		velocity.y = JUMP_VELOCITY
		$DreamerBody/Animator.set("parameters/jump/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
			
	if swing_timer > 0: swing_timer -= delta
	if combo_timer > 0:
		combo_timer -= delta
		if combo_timer <= 0:
			combo_hits = 0
			
	if Input.is_action_just_pressed("dodge") and (not dodging) and (input_dir.length() > 0):
		queue_swing = false
		dodging = true
		dodge_timer = 0.5
		dodge_direction = camera.transform.basis * Vector3(input_dir.x, 0, input_dir.y).normalized()
		
		$DreamerBody/Animator.set("parameters/dodge/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
		
	if (Input.is_action_just_pressed("attack") or queue_swing) and (not dodging) and (current_weapon.cooldown <= 0):
		if swing_timer > 0:
			if swing_timer < 0.1:
				queue_swing = true
		else:
			queue_swing = false
			
			swing_timer = get_my_weapon_info("swing_time")
			combo_timer = get_my_weapon_info("combo_timeout")
			if swing_timer == null: swing_timer = 0.0
			if combo_timer == null: combo_timer = 0.0
			
			var swooshy_id = get_my_weapon_info("attack_swooshy")
			if not swooshy_id: swooshy_id = "slash"
			
			
			var attack_swooshy = Global.effects.attack_swooshy[swooshy_id].instantiate()
			game.add_child(attack_swooshy)
			
			var attack_swooshy_scale = get_my_weapon_info("attack_swooshy_scale")
			if attack_swooshy_scale: attack_swooshy.scale = attack_swooshy_scale
				
			attack_swooshy.global_position = global_position
			attack_swooshy.global_rotation.y = $HitCollision.global_rotation.y + deg_to_rad(180)
			attack_swooshy.play_effect()
			
			$DreamerBody/Animator.set("parameters/swing_weapon/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
			
			var hits = $HitCollision.get_overlapping_bodies()
			
			var knockback = 0
			var damage = 0
			
			velocity = global_position.direction_to($HitCollision/Shape.global_position) * 4
			velocity.y = 0
			
			if get_my_weapon_info("combo_weapon"):
				var earned_combo_hit = false
				
				for body in hits:
					if body == self: continue
					
					if ("health" in body) and (body.health > 0):
						earned_combo_hit = true
						
				if earned_combo_hit: combo_hits += 1
				else: combo_hits = 0
						
				if combo_hits < get_my_weapon_info("hits_to_finish"):
					damage = get_my_weapon_info("damage_mid_combo")
					knockback = get_my_weapon_info("knockback_mid_combo")
				else:
					damage = get_my_weapon_info("damage")
					knockback = get_my_weapon_info("knockback")
					
					combo_hits = 0
					
					swing_timer = get_my_weapon_info("swing_time_combo_finish")
					if swing_timer == null: swing_timer = 0.0
			else:
				damage = get_my_weapon_info("damage")
				knockback = get_my_weapon_info("knockback")
				
				combo_hits = 0
			
			if get_my_weapon_info("ranged_weapon"):
				var projectile = get_my_weapon_info("projectile").instantiate()
				
				game.add_child(projectile)
				projectile.global_position = global_position
				projectile.rotation = $HitCollision.rotation
				
				projectile.pow()
			else:
				for body in hits:
					if body == self: continue
					
					if ("health" in body) and (body.health > 0):
						body.health -= damage
						
						var knockback_pos = global_position
						knockback_pos.y = 0
						var knockback_body_pos = $HitCollision/Shape.global_position
						knockback_body_pos.y = 0
						
						body.position.y += 0.2
						body.velocity.y = 0.4
						body.velocity += knockback_pos.direction_to(knockback_body_pos) * knockback
						
						if body.velocity.length() > knockback:
							body.velocity = body.velocity.normalized() * knockback
							
						if "mid_knockback" in body:
							body.mid_knockback = true
							
						if "on_knockback" in body:
							body.on_knockback()
							
						var damage_text = preload("res://scenes/effects/damage_text.tscn").instantiate()
						game.add_child(damage_text)
						damage_text.global_position = body.global_position
						damage_text.get_node("Label").text = str(floor(damage))
	
			if get_my_weapon_info("recharge_time"):
				current_weapon.cooldown = get_my_weapon_info("recharge_time")
	if dodging and (knockback_time <= 0):
		velocity.x = dodge_direction.x * 6
		velocity.z = dodge_direction.z * 6
		
		$DreamerBody/Animator.set("parameters/walk/blend_amount", 0)
		
		dodge_timer -= delta
		if dodge_timer <= 0: dodging = false
		
	elif direction and (knockback_time <= 0) and (swing_timer <= 0):
		velocity.x = direction.x * SPEED
		velocity.z = direction.z * SPEED
		
		$DreamerBody/Animator.set("parameters/walk/blend_amount", abs(direction.length()))
	else:
		
		velocity.x = move_toward(velocity.x, 0, delta * 24)
		velocity.z = move_toward(velocity.z, 0, delta * 24)
		
		$DreamerBody/Animator.set("parameters/walk/blend_amount", 0)
		
	if direction and is_on_floor():
		walk_animation_time += delta * 25
		
		$DreamerBody.position.y = sin(walk_animation_time + 1) / 16
		$DreamerBody.rotation.z = sin(walk_animation_time / 2) / 16
	else:
		walk_animation_time = 0
		
		$DreamerBody.rotation.z /= 1 + (delta * 2.5)
		
		$DreamerBody.position.y /= 1 + (delta * 12)
		
	if is_on_floor():
		$DreamerBody/Animator.set("parameters/fall/blend_amount", 0)
		$DreamerBody/Animator.set("parameters/leap/blend_amount", 0)
	else:
		if velocity.y < 0:
			$DreamerBody/Animator.set("parameters/fall/blend_amount", 1)
			$DreamerBody/Animator.set("parameters/leap/blend_amount", 0)
		else:
			$DreamerBody/Animator.set("parameters/fall/blend_amount", 0)
			$DreamerBody/Animator.set("parameters/leap/blend_amount", 1)

	move_and_slide() 
	
		
	$Shadow.global_position.y = $Floorcast.get_collision_point().y + 0.01
	
	$Label3D.text = str(velocity.length())
	
